image: atlassian/default-image:latest

pipelines:
  default:
    - step:
        name: "Mirror to GitHub without Jira tag and pipelines file"
        script:
          # Вывод значения GITHUB_USER для отладки (удалите после проверки)
          - "echo 'GITHUB_USER is: '$GITHUB_USER"
          - "echo 'Checking last commit message...'"
          # Получаем сообщение последнего коммита
          - "COMMIT_MSG=$(git log -1 --pretty=%B)"
          # Удаляем из сообщения вхождение 'OSP-8 ' (с пробелом после)
          - "NEW_COMMIT_MSG=$(echo \"$COMMIT_MSG\" | sed -E 's/OPS-[0-9]+ //g')"
          # Если сообщение изменилось, перезаписываем последний коммит
          - |
            if [ "$COMMIT_MSG" != "$NEW_COMMIT_MSG" ]; then
              echo "Updating commit message:"
              echo "Old: $COMMIT_MSG"
              echo "New: $NEW_COMMIT_MSG"
              git commit --amend -m "$NEW_COMMIT_MSG"
            else
              echo "No update needed."
            fi
          # Удаляем файл bitbucket-pipelines.yml, если он существует, чтобы он не попал в GitHub
          - |
            if [ -f "bitbucket-pipelines.yml" ]; then
              echo "Removing bitbucket-pipelines.yml for GitHub mirror..."
              git rm --cached bitbucket-pipelines.yml || true
              # Если есть изменения, делаем коммит с удалением файла
              git diff --cached --quiet || git commit -m "Remove bitbucket-pipelines.yml for GitHub mirror"
            else
              echo "bitbucket-pipelines.yml not found, skipping removal."
            fi
          - "echo 'Pushing changes to GitHub integ branch...'"
          # Пушим изменения в ветку integ на GitHub, подставляя переменные
          - "git push --force https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/BlessedDayss/M3App.git HEAD:integ"
