image: atlassian/default-image:latest

pipelines:
  default:
    - step:
        name: "Mirror to GitHub without Jira tag and pipelines file"
        script:
          - echo "GITHUB_USER is: $GITHUB_USER"
          - echo "Checking last commit message..."
          - COMMIT_MSG=$(git log -1 --pretty=%B)
          - echo "Old commit message: $COMMIT_MSG"
          - NEW_COMMIT_MSG=$(echo "$COMMIT_MSG" | sed -E 's/OPS-[0-9]+[ :\-]+//g')
          - echo "New commit message: $NEW_COMMIT_MSG"
          - bash -c '
            if [ "$COMMIT_MSG" != "$NEW_COMMIT_MSG" ] || git ls-files -- bitbucket-pipelines.yml > /dev/null; then
              if git ls-files -- bitbucket-pipelines.yml > /dev/null; then
                echo "Removing bitbucket-pipelines.yml for GitHub mirror..."
                git rm --cached bitbucket-pipelines.yml
              fi
              git commit --amend -m "$NEW_COMMIT_MSG"
            else
              echo "No changes needed."
            fi
          '
          - echo "Pushing changes to GitHub integ branch..."
          - git push --force https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/BlessedDayss/M3App.git HEAD:integ